config/routes.rb
Rails.application.routes.draw do

  resources :nota
  resources :alunos
  devise_for :usuarios
  resources :professors
  resources :cursos
  get 'home/index'

  root 'home#index'

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base

	belongs_to :curso
	validates :nome, :email, presence: true
		validates :ra, length: {minimum: 6}

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "85x70#" },
	:default_url => 'default.png'

	scope :por_nome, ->(nome) {
		where("nome LIKE ?", "%#{nome}%")
	}

end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    pesquisa = params[:p]
    @alunos = Aluno.por_nome(pesquisa)
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno Cadastrado com Sucesso!' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Registro Atualizado!' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Registro Excluído!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :ra, :rg, :cpf, :email, :image)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<%= form_for(@aluno, :html => { :multipart => true}) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="row">
    <div class="col-lg-5">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control"  %>
  </div>
 </div> 

  <div class="row">
    <div class="col-lg-3">
    <%= f.label :ra %><br>
    <%= f.text_field :ra, class: "form-control"  %>
  </div>
 </div> 

  <div class="row">
    <div class="col-lg-3">
    <%= f.label :rg %><br>
    <%= f.text_field :rg, class: "form-control" %>
  </div>
  </div>

   <div class="row">
    <div class="col-lg-4">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf, class: "form-control"  %>
  </div>
  </div>

   <div class="row">
    <div class="col-lg-5">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control"  %>
  </div>
  </div>
<br>
   <div class="row">
    <div class="col-lg-5">
    <%= f.label :imagem %><br>
    <%= f.file_field :image %>
  </div>
  </div>
  <br>

  <div class="actions">
    <%= f.submit "Cadastrar", class: "btn btn-primary"%>
    <%= link_to 'Voltar', alunos_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editar Registro</h1>

<%= render 'form' %>

app/views/alunos/index.html.erb
<h2>Alunos</h2>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="container col-xs-8">
    <%= link_to 'Novo Aluno', new_aluno_path,class: 'btn btn-success btn-lg col-lg-3' %>
  </div>

<div class="col-xs-4 text-right">
    <%= form_tag(alunos_path, method: "get") do %>
      <div class="input-group">
        <%= text_field_tag(:p, '', class: 'form-control') %>
        <span class="input-group-btn">
          <%= button_tag class: 'btn btn-success' do %>
            <i class="fa fa-search" aria-hidden="true"></i>
          <% end %>
        </span>
      </div>
    <% end %>
  </div>
 </div>
 <br>

<table class= "table table-striped">
  <thead>
    <tr>
      <th>Imagem</th>
      <th>Nome</th>
      <th>Ra</th>
      <th>Rg</th>
      <th>Cpf</th>
      <th>Email</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= image_tag(aluno.image.url(:thumb), class: "img-circle" ) %></td>
        <td><%= aluno.nome %></td>
        <td><%= aluno.ra %></td>
        <td><%= aluno.rg %></td>
        <td><%= aluno.cpf %></td>
        <td><%= aluno.email %></td>
        <td><%= link_to 'Mostrar', aluno, class: "btn btn-default" %>
        <%= link_to 'Editar', edit_aluno_path(aluno), class: "btn btn-primary" %>
        <%= link_to 'Excluir', aluno, class: "btn btn-danger", method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/alunos/new.html.erb
<h1>Novo Aluno</h1>

<%= render 'form' %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<p class="lead">
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p class= "lead">
  <strong>Ra:</strong>
  <%= @aluno.ra %>
</p>

<p class= "lead">
  <strong>Rg:</strong>
  <%= @aluno.rg %>
</p>

<p class= "lead">
  <strong>Cpf:</strong>
  <%= @aluno.cpf %>
</p>

<p class="lead">
  <strong>Email:</strong>
  <%= @aluno.email %>
</p>

<div>
<p class="lead">
  <%= image_tag(@aluno.image, class: "img-circle img-circle-show") %>
</p>
</div>

<%= link_to 'Editar', edit_aluno_path(@aluno), class: "btn btn-primary btn-lg col-sm-2" %>
<%= link_to 'Voltar', alunos_path, class: "btn btn-default btn-lg col-sm-2" %>


</div>