config/routes.rb
Rails.application.routes.draw do

  resources :nota
  resources :alunos
  devise_for :usuarios
  resources :professors
  resources :cursos
  get 'home/index'

  root 'home#index'

end

app/models/curso.rb
class Curso < ActiveRecord::Base
	has_many :aluno
	has_many :professor
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Registro Atualizado!' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Registro Excluído!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nome, :area)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= form_for(@curso) do |f| %>
  <% if @curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% @curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-lg-5">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
</div>

<br>
<div class="row">
  <div class="col-lg-5">
    <%= f.label :area %><br>
    <%= f.text_field :area, class: "form-control" %>
  </div>
</div>

<br>
  <div class="actions">
    <%= f.submit "Registrar", class: "btn btn-primary"%>
    <%= link_to 'Voltar', cursos_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editar Registro</h1>

<%= render 'form' %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Cursos</h2>


  <%= link_to 'Novo Curso', new_curso_path,class: 'btn btn-success btn-lg col-sm-2' %>
  <br>
  <br>
  <br>

<table class= "table table-striped text-center">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Area</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td class="text-left"><%= curso.nome %></td>
        <td><%= curso.area %></td>
        <td><%= link_to 'Mostrar', curso, class: 'btn btn-default' %>
        <%= link_to 'Editar', edit_curso_path(curso), class: 'btn btn-primary' %>
        <%= link_to 'Excluir', curso, class: 'btn btn-danger' , method: :delete, data: { confirm: 'Você tem certeza ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cursos/new.html.erb
<div class="page-header">
	<h1>Novo Curso</h1>
</div>
<%= render 'form' %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p class="lead">
  <strong>Nome:</strong>
  <%= @curso.nome %>
</p>

<p class="lead">
  <strong>Area:</strong>
  <%= @curso.area %>
</p>
<div>
	<%= link_to 'Editar', edit_curso_path(@curso), class: "btn btn-primary btn-lg" %> 
	<%= link_to 'Voltar', cursos_path, class: "btn btn-default btn-lg" %>
</div>