config/routes.rb
Rails.application.routes.draw do

  resources :nota
  resources :alunos
  devise_for :usuarios
  resources :professors
  resources :cursos
  get 'home/index'

  root 'home#index'

end

app/controllers/nota_controller.rb
class NotaController < ApplicationController
  before_action :set_notum, only: [:show, :edit, :update, :destroy]

  # GET /nota
  # GET /nota.json
  def index
    @nota = Notum.all
  end

  # GET /nota/1
  # GET /nota/1.json
  def show
  end

  # GET /nota/new
  def new
    @notum = Notum.new
  end

  # GET /nota/1/edit
  def edit
  end

  # POST /nota
  # POST /nota.json
  def create
    @notum = Notum.new(notum_params)

    respond_to do |format|
      if @notum.save
        format.html { redirect_to @notum, notice: 'Nota lançada com sucesso!' }
        format.json { render :show, status: :created, location: @notum }
      else
        format.html { render :new }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota/1
  # PATCH/PUT /nota/1.json
  def update
    respond_to do |format|
      if @notum.update(notum_params)
        format.html { redirect_to @notum, notice: 'Nota corrigida com sucesso!' }
        format.json { render :show, status: :ok, location: @notum }
      else
        format.html { render :edit }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota/1
  # DELETE /nota/1.json
  def destroy
    @notum.destroy
    respond_to do |format|
      format.html { redirect_to nota_url, notice: 'Nota apagada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notum
      @notum = Notum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notum_params
      params.require(:notum).permit(:curso_id, :aluno_id, :professor_id, :data, :nota1, :nota2, :nota3)
    end
end

app/helpers/nota_helper.rb
module NotaHelper
end

app/views/nota/_form.html.erb
<%= form_for(@notum) do |f| %>
  <% if @notum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notum.errors.count, "error") %> prohibited this notum from being saved:</h2>

      <ul>
      <% @notum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
<div class="col-sm-3">
    <%= f.label :curso%><br>
    <%= f.collection_select :curso, Curso.all, :id, :nome, {prompt: "Selecione um curso"}, {class: "form-control"} %>
  </div>
  <div class="col-sm-4">
    <%= f.label :aluno %><br>
    <%= f.collection_select :aluno, Aluno.all, :id, :nome, {prompt: "Selecione um aluno"}, {class: "form-control"} %>
  </div>
  <div class="col-sm-3">
    <%= f.label :professor_id %><br>
    <%= f.collection_select :professor, Professor.all, :id, :nome, {prompt: "Selecione um professor"}, {class: "form-control"} %>
  </div>
</div><br><br><br>

<div class="row">
  <div class="col-lg-3">
    <%= f.label :data , "Data de Lançamento da Nota" %><br>
    <%= f.date_field :data, class: "form-control" %>
  </div>
  <div class="col-sm-1">
    <%= f.label :nota1, "Avaliação 1" %><br>
    <%= f.number_field :nota1, class: "form-control" %>
  </div>
  <div class="col-sm-1">
    <%= f.label :nota2, "Avaliação 2" %><br>
    <%= f.number_field :nota2, class: "form-control" %>
  </div>
  <div class="col-sm-1">
    <%= f.label :nota3, "Trabalho em Grupo", class: "tgrupo" %><br>
    <%= f.number_field :nota3, class: "form-control" %>
  </div>
 </div> 
  <br><br>
  <div class="actions">
    <%= f.submit "Registrar Nota", class: "btn-lg btn btn-success" %>
    <%= link_to 'Voltar', nota_path, class: "btn-lg btn btn-default" %>
  </div>

<% end %>

app/views/nota/edit.html.erb
<h1>Editing Notum</h1>

<%= render 'form' %>

app/views/nota/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Últimas Notas Lançadas</h1>
<br>
<%= link_to 'Inserir Nota', new_notum_path, class: "btn btn-success btn-lg" %>


<table class= "table table-striped">
  <thead>
    <tr>
      <th>Curso</th>
      <th>Aluno</th>
      <th>Professor</th>
      <th>Data</th>
      <th>Nota1</th>
      <th>Nota2</th>
      <th>Nota3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nota.each do |notum| %>
      <tr>
        <td><%= notum.curso.nome %></td>
        <td><%= notum.aluno.nome %></td>
        <td><%= notum.professor.nome %></td>
        <td><%= notum.data %></td>
        <td><%= notum.nota1 %></td>
        <td><%= notum.nota2 %></td>
        <td><%= notum.nota3 %></td>
        <td><%= link_to 'Exibir Nota', notum, class: "btn btn-default" %>
        <%= link_to 'Corrigir Nota', edit_notum_path(notum), class: "btn btn-primary" %>
        <%= link_to 'Apagar Nota', notum, method: :delete, data: { confirm: 'Deseja apagar esta nota?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/nota/new.html.erb
<h1>Inserir Nota</h1>

<%= render 'form' %>

app/views/nota/show.html.erb
<p id="notice"><%= notice %></p>

<p class="lead">
  <strong>Curso:</strong>
  <%= @notum.curso.nome %>
</p>

<p class="lead" >
  <strong>Aluno:</strong>
  <%= @notum.aluno.nome %>
</p>

<p class="lead">
  <strong>Professor:</strong>
  <%= @notum.professor.nome %>
</p>

<p class="lead">
  <strong>Data:</strong>
  <%= @notum.data %>
</p>

<p class="lead">
  <strong>Nota1:</strong>
  <%= @notum.nota1 %>
</p>

<p class="lead">
  <strong>Nota2:</strong>
  <%= @notum.nota2 %>
</p>

<p class="lead">
  <strong>Nota3:</strong>
  <%= @notum.nota3 %>
</p>

<%= link_to 'Alterar', edit_notum_path(@notum), class: "btn btn-primary btn-lg" %>
<%= link_to 'Voltar', nota_path, class: "btn btn-default btn-lg" %>