config/routes.rb
Rails.application.routes.draw do

  resources :nota
  resources :alunos
  devise_for :usuarios
  resources :professors
  resources :cursos
  get 'home/index'

  root 'home#index'

end

app/models/professor.rb
class Professor < ActiveRecord::Base
	has_many :curso
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor cadastrado!' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Registro Atualizado!.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Registro Excĺuído' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:nome, :registro, :disciplina)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professors from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>
  <div class="row">
    <div class="col-lg-5">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  </div>

<div class="row">
  <div class="col-lg-3">
    <%= f.label :registro %><br>
    <%= f.text_field :registro, class: "form-control" %>
  </div>
  </div>

<div class="row">
  <div class="col-lg-4">
    <%= f.label :disciplina %><br>
    <%= f.text_field :disciplina, class: "form-control" %>
  </div>
  </div>

<br>
  <div class="row">

  <div class="actions col-lg-5">
    <%= f.submit "Salvar", class: "btn btn-primary"%>
    <%= link_to 'Voltar', professors_path, class: "btn btn-default" %>
  </div>
  </div>
 </div> 
<% end %>

app/views/professors/edit.html.erb
<h1>Editar Registro</h1>

<%= render 'form' %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Professores</h2>
<%= link_to 'Novo Professor', new_professor_path,class: 'btn btn-success btn-lg col-sm-2' %>
<br>

<table class= 'table table-striped'>  
  <br><br>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Registro</th>
      <th>Disciplina</th>
      <th class="text-center">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td class="text-left"><%= professor.nome %></td>
        <td><%= professor.registro %></td>
        <td><%= professor.disciplina %></td>
        <td class="text-center">
        <%= link_to 'Mostrar', professor, class: 'btn btn-default' %>
        <%= link_to 'Editar', edit_professor_path(professor), class: 'btn btn-primary' %>
        <%= link_to 'Excluir', professor, class: 'btn btn-danger', method: :delete, data: { confirm: 'Confirma exclusão ?' } %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/professors/new.html.erb
<div class="page-header">
	<h1>Cadastrar Novo Professor</h1>
</div>
<%= render 'form' %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<p class="lead">
  <strong>Nome:</strong>
  <%= @professor.nome %>
</p>

<p class="lead">
  <strong>Registro:</strong>
  <%= @professor.registro %>
</p>

<p class="lead">
  <strong>Disciplina:</strong>
  <%= @professor.disciplina %>
</p>

<%= link_to 'Editar', edit_professor_path(@professor), class: "btn btn-primary btn-lg" %> 
<%= link_to 'Voltar', professors_path, class: "btn btn-default btn-lg" %>
</div>